### ISSUE TITLE
パッケージを入れた状態でアバターをビルドすると失敗する

### ISSUE THREAD

**Issue by halby24** [sayunana/lilToon2MToon#1]
他の環境でも起こるかどうかはわかりませんが、自分の環境ではアバタービルド時にusing lilToon;などがインポートエラーを起こしてビルドに失敗してしまいます。

lilToon2Mtoon.cs全体を#if UNITY_EDITOR節で囲むと起こらなくなります。

環境
Unity 2022.3.22f1
lilToon [#5ed3507](https://github.com/lilxyzw/lilToon/commit/5ed3507003b3cf92eb1879a92a30408615134781)
VRCSDK 3.6.1

**Comment by sayunana** [comment]
情報提供あがとうございます。
こちらの環境でも同様にビルド時にインポートエラーが出ることを確認しました。
バージョン0.2.0で修正いたしましたのでご確認お願いします。
